export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_USER = "SET_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const EMAIL_CONFIRMED = "EMAIL_CONFIRMED";
export const WAIT_FOR_CONFIRMATION = "WAIT_FOR_CONFIRMATION";
